name: "Add labels to issue or PR"
description: "An action to add labels to issue or PR."
author: "Bright Ran"

inputs:
  repository:
    description: "The name of the repository which the issue or PR is in. For example, ActionsRML/add-labels-to-issue"
    required: true
    default: ${{ github.repository }}
  issue_numbers:
    description: "The number of the issue or PR."
    required: true
    default: "current"
  labels:
    description: "The labels to add."
    required: true
  token:
    description: "The Personal access token (PAT) used to authenticate."
    default: ${{ github.token }}

runs:
  using: "node12"
  main: "dist/index.js"

branding:
  icon: "edit"
  color: "blue"
